In [1]:
import pandas as pd
import numpy as np

In [2]:
beers_df = pd.read_csv("./cervezas.csv", sep=";")
beers_df

Cajas  Distancia  Tiempo
0      10         30      24
1      15         25      27
2      10         40      29
3      20         18      31
4      25         22      25
5      18         31      33
6      12         26      26
7      14         34      28
8      16         29      31
9      22         37      39
10     24         20      33
11     17         25      30
12     13         27      25
13     30         23      42
14     24         33      40

In [3]:
from min_sqrs import min_sqrs

In [4]:
def add_bias(X: np.ndarray) -> np.ndarray:
    b_X = np.ones((X.shape[0], X.shape[1] + 1))
    b_X[:, :-1] = X
    return b_X

In [5]:
X = beers_df[["Cajas", "Distancia"]].to_numpy()
X = add_bias(X)
X

array([[10., 30.,  1.],
       [15., 25.,  1.],
       [10., 40.,  1.],
       [20., 18.,  1.],
       [25., 22.,  1.],
       [18., 31.,  1.],
       [12., 26.,  1.],
       [14., 34.,  1.],
       [16., 29.,  1.],
       [22., 37.,  1.],
       [24., 20.,  1.],
       [17., 25.,  1.],
       [13., 27.,  1.],
       [30., 23.,  1.],
       [24., 33.,  1.]])

In [6]:
Y = beers_df[["Tiempo"]].to_numpy()
Y

array([[24],
       [27],
       [29],
       [31],
       [25],
       [33],
       [26],
       [28],
       [31],
       [39],
       [33],
       [30],
       [25],
       [42],
       [40]])

In [7]:
linear_f = lambda x : x
constant_f = lambda _ : 1

In [8]:
K_fs = [linear_f, linear_f, constant_f]

In [9]:
K = min_sqrs(X, K_fs, Y)
K

array([[ 0.33684211],
       [-0.47368421],
       [32.73684211]])

In [10]:
f = lambda x1, x2 : K[0]*x1 + K[1]*x2 + K[2]

In [11]:
vec_f = np.vectorize(f)

In [12]:
F = vec_f(X[:,0], X[:,1])
F = F.reshape((F.size, 1))
F

array([[21.89473684],
       [25.94736842],
       [17.15789474],
       [30.94736842],
       [30.73684211],
       [24.11578947],
       [24.46315789],
       [21.34736842],
       [24.38947368],
       [22.62105263],
       [31.34736842],
       [26.62105263],
       [24.32631579],
       [31.94736842],
       [25.18947368]])

In [13]:
error = Y - F
error

array([[ 2.10526316],
       [ 1.05263158],
       [11.84210526],
       [ 0.05263158],
       [-5.73684211],
       [ 8.88421053],
       [ 1.53684211],
       [ 6.65263158],
       [ 6.61052632],
       [16.37894737],
       [ 1.65263158],
       [ 3.37894737],
       [ 0.67368421],
       [10.05263158],
       [14.81052632]])

In [14]:
mse = error.transpose().dot(error).item() / error.size
mse

63.41444875346102